#!/usr/bin/env python3
"""Write docs/data.js from the sweep results."""
from __future__ import annotations
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
CANDIDATES = [ROOT / "data" / "results.json", ROOT / "results.json", ROOT / "sweep" / "results.json"]


def main(allow_fixture: bool = False) -> int:
    # Check the fields the page reads before writing anything. A page that renders a
    # missing field as "n/a" looks identical to one whose measurement came out empty,
    # and that class of bug has already survived several verification passes on the
    # sibling project in this campaign.
    try:
        import check_contract
        check_contract.main()
        print("---")
    except Exception as exc:
        print(f"  contract check could not run: {exc}")

    src = next((p for p in CANDIDATES if p.exists()), None)
    if src is None:
        raise SystemExit("no results.json found in " + ", ".join(str(p) for p in CANDIDATES))
    d = json.loads(src.read_text())

    # The evaluation set decides what the page may claim, so the check on it travels
    # with the results rather than being described in prose written by hand. If the
    # check has not been run, the page says the question is open instead of assuming.
    check = ROOT / "data" / "labelling_check.json"
    if check.exists():
        d["labelling_check"] = json.loads(check.read_text())

    # The per-clip counts behind the published-weights baseline, so the page can add
    # them up in the browser and show that its headline is the sum of its own parts
    # rather than a number that was typed. Only the counts travel: no clip content.
    base = ROOT / "data" / "baseline_real.json"
    if base.exists():
        b = json.loads(base.read_text())
        d["baseline_per_clip"] = {
            "dtw_cutoff": b.get("dtw_cutoff"),
            "stated": {k: b.get(k) for k in ("labels", "found", "predictions", "recall", "precision", "median_adtw_px")},
            "sections": {
                k: {"labels": v["labels"], "found": v["found"],
                    "predictions": v["predictions"], "claimed": v["claimed"]}
                for k, v in (b.get("per_section") or {}).items()
            },
        }

    # Refuse to write fixture content into docs/ at all. The page has a runtime guard,
    # but a guard that fires in the browser does not stop `git add -A` from committing
    # the file, which is exactly what happened once. The only safe place to stop it is
    # before it is written. --allow-fixture exists for layout checks and says so loudly.
    blob = json.dumps(d)
    mark = re.search(r"fixture|placeholder|lorem ipsum|TODO", blob, re.I)
    if mark and not allow_fixture:
        print(f"REFUSING to write docs/data.js: the word {mark.group(0)!r} appears in the study "
              f"output, so this is not a result. Pass --allow-fixture to write it anyway for a "
              f"layout check, and delete docs/data.js afterwards.")
        return 2
    if mark:
        print(f"writing FIXTURE data because --allow-fixture was passed ({mark.group(0)!r} found). "
              f"Delete docs/data.js when the check is done.")

    DOCS.mkdir(parents=True, exist_ok=True)
    out = "/* generated by study/build_page_data.py, do not edit */\nconst D = " + \
        json.dumps(d, separators=(",", ":")) + ";\n"
    (DOCS / "data.js").write_text(out)
    cfg = d.get("configs") or []
    done = [c for c in cfg if c.get("real_score") is not None]
    print(f"wrote docs/data.js from {src.name}: {len(done)} of {len(cfg)} configurations scored")
    return 0


if __name__ == "__main__":
    raise SystemExit(main("--allow-fixture" in sys.argv))
